### PR TITLE
Overhauled the implementations.

### PR DESCRIPTION
**Pull request by hbina**
Trying to learn about RIFF format and Rust in general. I have made some changes to the codebase that might be of interest to you. It exposes a `RIFF` data type that can be used to navigate through the file which is a lot easier than passing around `file` every time I want to access something.

### CODE REVIEW

**Comment by frabert** [comment]
Hi Hanif, thanks for taking the time of doing this!
Unfortunately, I find that your proposal goes against two principles (which I have never stated, I admit) which I followed while designing the API, namely that no read should occur until it is strictly needed and that interpreting the contents of chunks should be completely left to the user.

For instance, `ChunkContents::from(Chunk)` assumes that the user would actually want to follow the recursive structure of the RIFF file, and eagerly reads and parses the whole file, potentially. This is problematic because
1) the user might actually only want _some_ data (think of an AVI file -- reading it whole in memory would hog a lot of memory)
2) the file might not be completely well-formed, which would crash the parser

These are both issues I've run into with the previous API (before 1.0), which motivated the current design

**Comment by hbina** [comment]
Hmm that's a reasonable approach to this problem.

I do admit that my implementation reads the entire file into resident memory which might not even be possible for large 4K movies or whatever.

I still think that wrapping the entire library internals inside a `Riff` struct is a good thing so that the user does not have to keep around the `File` themselves. I think it is reasonable that a library holds on to the file that its been asked to parse? Right now, its entirely possible (I think) for the user to wrongly pass the wrong file and the library would have no way of verifying that they are correct.

Just my 2 cent!

**Comment by hbina** [comment]
Hello @frabert 
I have since implemented a version of my fork that also reads lazily into the file.
https://github.com/hbina/riff/blob/master/src/riff_disk.rs
Let me know what you think :)

**Comment by frabert** [comment]
That looks good! Here are my thoughts:

- The `Riff` struct looks superfluous right now, I'd rather have the `from_file` method integrated into `Chunk`
- I'm not sure why we need two different iterators for typed and untyped chunks
- I dont like the `Chunk::get_child_*` and `Chunk::get_raw_child_*` methods: to me `Chunk` should only have a way to iterate over its children, get its id, type, size and contents

I like not having to pass the reader every time!

**Pull request closed without merging**
